// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $quotes_add from "./routes/quotes/add.tsx";
import * as $quotes_index from "./routes/quotes/index.tsx";
import * as $quotes_read from "./routes/quotes/read.tsx";
import * as $ImageTextDetector from "./islands/ImageTextDetector.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/quotes/add.tsx": $quotes_add,
    "./routes/quotes/index.tsx": $quotes_index,
    "./routes/quotes/read.tsx": $quotes_read,
  },
  islands: {
    "./islands/ImageTextDetector.tsx": $ImageTextDetector,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
