name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    # Skip deployment if the commit message contains [skip deploy]
    if: contains(github.event.head_commit.message, '[skip deploy]') == false
    runs-on: ubuntu-latest

    permissions:
      # Needed for auth with Deno Deploy
      id-token: write
      # Needed to clone the repository
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build step
        run: "deno run build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "quotesaver"
          entrypoint: "./main.ts"
          root: ""
